### ISSUE TITLE
Wrong Key Features Description

### ISSUE THREAD

**Issue by Al-Amin-Khan-Shakil** [Ayokunnumi1/To-do-list#2]
![image](https://github.com/Ayokunnumi1/To-do-list/assets/127226176/44eb98e1-04e6-47d5-9c2e-022f3fa042f5)
### As you can see above your key feature description is wrong. Please update the correct key feature description of your project. Because it helps people to understand your project better.

**Comment by Ayokunnumi1** [comment]
Thanks for the feedback
