### ISSUE TITLE
Remove live demo

### ISSUE THREAD

**Issue by Al-Amin-Khan-Shakil** [Ayokunnumi1/To-do-list#5]
![image](https://github.com/Ayokunnumi1/To-do-list/assets/127226176/2c5d83bf-e83e-46a6-8f9b-b51ede27c2cc)
Hi, your readme looks well documented, Good Job! But you need to make a little adjustment you can just remove the live demo from the list table of contents because there is no live demo link or content in your document.

**Comment by Ayokunnumi1** [comment]
Alright! thanks for sighting the issue. I have corrected it
